Repository FAIRplus/the-fair-cookbook, pull requests merged in 2022-05, with the labels that each got.

#434 Open refine recipe and review
  _bibliography/bibliography-faircookbook.bib
  _toc.yml
  content/recipes/infrastructure/openrefine-nvt.md
  images/openrefine-wiki-reconci.png
  images/openrefine.png
  images/rdf-align-karma.png
  images/rdf-align-openrefine.png
  images/wikidraftworks.png
Labels: editor's task: hand recipe to review, editor's task: followup on recipe writing progress, author's task: write recipe, author's task: incorporate review comments

#431 Update KG content and add new publications
  _bibliography/bibliography-faircookbook.bib
  content/recipes/introduction/public-kg-resource-integration.md
Labels: editor's task: assess review&initialize next steps, editor's task: editorial review and merge

#432 Fx kg copied from main
  content/recipes/introduction/FAIR-and-knowledge-graphs.md
Labels: author's task: incorporate review comments, editor's task: editorial review and merge
